"""Initial migration

Revision ID: 7d50c8c02c7e
Revises: 
Create Date: 2026-05-01 14:02:52.039819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d50c8c02c7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama_barang', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barang_nama_barang'), 'barang', ['nama_barang'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PETUGAS', 'PENCARI', name='roleenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_table('inventaris',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('barang_id', sa.String(length=36), nullable=True),
    sa.Column('jumlah_barang', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barang_id')
    )
    op.create_table('laporan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('barang_id', sa.String(length=36), nullable=True),
    sa.Column('jenis', sa.Enum('KEHILANGAN', 'PENEMUAN', name='jenislaporanenum'), nullable=True),
    sa.Column('nama_pelapor', sa.String(), nullable=True),
    sa.Column('waktu_pelaporan', sa.DateTime(), nullable=True),
    sa.Column('lokasi', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DIBUAT', 'DIPROSES', 'SELESAI', name='statuslaporanenum'), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_aktivitas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.Column('aksi', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_aktivitas')
    op.drop_table('laporan')
    op.drop_table('inventaris')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_barang_nama_barang'), table_name='barang')
    op.drop_table('barang')
    # ### end Alembic commands ###
