"""refactor database schema

Revision ID: caba18bc71c4
Revises: 7d50c8c02c7e
Create Date: 2026-05-01 14:34:39.990047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caba18bc71c4'
down_revision: Union[str, Sequence[str], None] = '7d50c8c02c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riwayat_penyerahan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('laporan_id', sa.String(length=36), nullable=True),
    sa.Column('petugas_id', sa.String(length=36), nullable=True),
    sa.Column('nama_barang', sa.String(), nullable=True),
    sa.Column('penerima', sa.String(), nullable=True),
    sa.Column('tanggal_selesai', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laporan_id'], ['laporan.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laporan_id')
    )
    op.drop_constraint('laporan_barang_id_fkey', 'laporan', type_='foreignkey')
    op.drop_column('laporan', 'barang_id')
    op.drop_table('inventaris')
    op.drop_index(op.f('ix_barang_nama_barang'), table_name='barang')
    op.drop_table('barang')
    op.add_column('laporan', sa.Column('nama_barang', sa.String(), nullable=True))
    op.add_column('laporan', sa.Column('kategori', sa.String(), nullable=True))
    op.add_column('laporan', sa.Column('foto', sa.String(), nullable=True))
    op.create_index(op.f('ix_laporan_nama_barang'), 'laporan', ['nama_barang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laporan', sa.Column('barang_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('laporan_barang_id_fkey'), 'laporan', 'barang', ['barang_id'], ['id'])
    op.drop_index(op.f('ix_laporan_nama_barang'), table_name='laporan')
    op.drop_column('laporan', 'foto')
    op.drop_column('laporan', 'kategori')
    op.drop_column('laporan', 'nama_barang')
    op.create_table('barang',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('nama_barang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kategori', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foto', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('barang_pkey'))
    )
    op.create_index(op.f('ix_barang_nama_barang'), 'barang', ['nama_barang'], unique=False)
    op.create_table('inventaris',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('barang_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('jumlah_barang', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang.id'], name=op.f('inventaris_barang_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventaris_pkey')),
    sa.UniqueConstraint('barang_id', name=op.f('inventaris_barang_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('riwayat_penyerahan')
    # ### end Alembic commands ###
